---
- name: copy module demo
  hosts: all
  become: true
  tasks:
    - name: copy ping.yml
      ansible.builtin.copy:
        src: ~/Desktop/ansible/AnsibleTutorial/ping.yml
        dest: /home/ping.yml
        owner: basheer
        mode: '0644'
...
