---
- name: cron module demo
  hosts: all
  become: true
  tasks:
    - name: install cron
      ansible.builtin.apt:
        name: cron
        state: latest

    - name: "example cronjob"
      ansible.builtin.cron:
        name: "test"
        state: present
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: 'logger "ansible-pilot"'
...
