---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/new_file.txt"

  tasks:
    - name: Creating am empty file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
...
