---
- name: check if a file exists
  hosts: all
  become: false
  vars:
    myfile: /home/simone/example.txt
  tasks:
    - name: check if a file exists
      ansible.builtin.stat:
        path: "{{ myfile }}"
      register: file_data

    - name: report file exists
      ansible.builtin.debug:
        msg: "The file {{ myfile }} exists"
      when: file_data.stat.exists

    - name: report a file not exists
      ansible.builtin.debug:
        msg: "The file {{ myfile }} doesn't exist"
      when: not file_data.stat.exists
...
