---
- name: Installs a package and prints the result
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        name: wget
        state: latest
      register: install_result

    - name: debug
      ansible.builtin.debug:
        var: install_result
...
