---

- hosts: web_servers
  become: true
  tasks:
  - name: update and upgrade and install mariadb
    tags: update
    package:
      name:
        - mariadb-server
      update_cache: yes

  - name: copy files
    tags: update,files
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: install packages
    tags: install
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

- hosts: all
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
