---
- name: synchronize module demo
  hosts: all
  become: false
  vars:
    source: '/home/basheer/Desktop/ansible/TerraformTutorial'
    destination: '/home/simone/terraform'
  tasks:
    - name: rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true

    - name: data synchronization
      ansible.posix.synchronize:
        src: '{{ source }}'
        dest: '{{ destination }}'
...
