---
- name: unarchive module demo
  hosts: all
  become: true
  vars:
    myurl: "https://github.com/archive/lucab85/ansible-pilot/archive/refs/heads/master.zip"
  tasks:
    - name: extractor presents
      ansible.builtin.apt:
        name:
          - unzip
          - tar
    - name: extractor archive
      ansible.builtin.unarchive:
        src: "{{ myurl }}"
        dest: "/home/simone/"
        remote_src: true
        validate_certs: true
...
